name: "financial_analytics"
version: "1.0.0"
config-version: 2

profile: "financial_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  financial_analytics:
    +generate_schema_name: false
  # Bronze Layer - Ingestion - Raw data ingestion
  ingestion:
    +materialized: table
    +schema: bronze
    +tags: ["bronze"]

  # Silver Layer - Transform - Cleaned and standardized
  transform:
    +materialized: table
    +schema: silver
    +tags: ["silver"]

  # Gold Layer - Serving - Kimball dimensional model
  serving:
    +schema: gold
    +tags: ["gold", "serving"]

    # Dimensions folder
    dimensions:
      +materialized: table
      +tags: ["dimension"]

    # Facts folder
    facts:
      +materialized: incremental
      +tags: ["fact"]
      +on_schema_change: append_new_columns

    # Analytics folder
    analytics:
      +materialized: view
      +tags: ["analytics"]

vars:
  # Business rules
  fraud_threshold: 0.7
  high_risk_amount: 10000
  churn_risk_threshold: 0.6
  delinquent_days: 30

  # Date parameters
  lookback_days: 90

seeds:
  +schema: bronze
  +tags: ["seed"]

snapshots:
  +target_schema: silver
  +strategy: timestamp
  +updated_at: updated_at
  +tags: ["snapshot", "scd"]
