financial_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('DB_USER', 'analytics_user') }}"
      password: "{{ env_var('DB_PASSWORD', 'analytics_password') }}"
      port: 5432
      dbname: finance_analytics
      schema: public
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,bronze,silver,gold

    prod:
      type: postgres
      host: "{{ env_var('PROD_DB_HOST') }}"
      user: "{{ env_var('PROD_DB_USER') }}"
      password: "{{ env_var('PROD_DB_PASSWORD') }}"
      port: 5432
      dbname: financial_analytics_prod
      schema: public
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,bronze,silver,gold
